[package]
name = "data-resource"
version = "0.1.0"
edition = "2021"

[lib]
name = "data_resource"
crate-type = ["rlib"]
bench = false

[dependencies]
data-error = { path = "../data-error" }
serde = { version = "1.0", features = ["derive"] }
