[package]
name = "rpc_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "rpc_core"

[dependencies]
serde.workspace = true
serde_json = "1.0.121"
uniffi = "0.28.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
once_cell = "1.19.0"
