name: Build CLI tool

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Build ARK-CLI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt, clippy

      - name: Check
        run: cargo check

      - name: Format
        run: |
          cargo fmt --all -- --check
          cargo clippy 

      - name: Build Release
        run: cargo build --verbose --release
