name: Build CLI tool

on: [push]

env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: Build ARK-CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Check
        run: cargo check

      - name: Format
        run: cargo fmt --all -- --check

      - name: Build Release
        run: cargo build --verbose --release
