/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileStorage */

#ifndef _Included_FileStorage
#define _Included_FileStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileStorage
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_FileStorage_create
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     FileStorage
 * Method:    set
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_FileStorage_set
  (JNIEnv *, jclass, jstring, jstring, jlong);

/*
 * Class:     FileStorage
 * Method:    remove
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_FileStorage_remove
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     FileStorage
 * Method:    needsSyncing
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_FileStorage_needsSyncing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     FileStorage
 * Method:    readFS
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_FileStorage_readFS
  (JNIEnv *, jclass, jlong);

/*
 * Class:     FileStorage
 * Method:    writeFS
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_FileStorage_writeFS
  (JNIEnv *, jclass, jlong);

/*
 * Class:     FileStorage
 * Method:    erase
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_FileStorage_erase
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
