[workspace]

members = [
    "core",
    "uniffi-bindgen",
]
resolver = "2"

[workspace.dependencies]
serde = "1.0.204"
uniffi = "0.28.0"

[workspace.build-dependencies]
uniffi = { version = "0.28.0", features = [ "build" ] }