name: Cache build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: true

      - name: Run tests
        run: cargo test --workspace --verbose --release

  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: true

      - name: Run tests
        run: cargo test --workspace --verbose --release

  mac-intel:
    name: MacOS Intel
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: true

      - name: Run tests
        run: cargo test --workspace --verbose --release

  mac-arm:
    name: MacOS ARM
    runs-on: macos-13-xlarge

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: true

      - name: Run tests
        run: cargo test --workspace --verbose --release
