name: Main Branch Workflow

on:
  push:
    branches:
      - main
  schedule:
    # Run each week
    - cron: "0 0 * * 0"

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --workspace --verbose --release

  windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --workspace --verbose --release

  mac-arm:
    name: MacOS ARM
    runs-on: macos-13-xlarge

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --workspace --verbose --release
