name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Debug
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build Release
      run: cargo build --verbose --release

