name: Verify build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Build ArkLib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Check
        run: cargo check

      - name: Format
        run: cargo fmt --all -- --check

      - name: Build Debug
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build Release
        run: cargo build --verbose --release
